src/main/02-ecr.tf
src/main/env/uat/terraform.tfvars

Enable apigw public dns 

---

src/main/01-network.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/uat/terraform.tfvars
src/main/outputs.tf

Vpc peering route tabe

---

src/init/env/prod/backend.tfvars
src/init/env/prod/terraform.tfvars
src/main/env/prod/backend.tfvars
src/main/env/prod/terraform.tfvars

Prod config

---

src/main/env/prod/terraform.tfvars

api tokenizer rate limits

---

src/main/32-api-tokenizer.tf
src/main/README.md

Api cloudwatch alerts

---

src/main/env/uat/terraform.tfvars

New api keys for pnpf

---

src/main/32-api-tokenizer.tf
src/main/README.md

Api path with stage

---

src/azuredevops/.terraform.lock.hcl
src/azuredevops/00-main.tf
src/azuredevops/01-project.tf
src/azuredevops/02-pipelines.tf
src/azuredevops/03-secrets.tf
src/azuredevops/04-service_connections.tf
src/azuredevops/98-variables.tf
src/azuredevops/99-outputs.tf
src/azuredevops/README.md
src/init/terraform.sh
src/pipelines/deploy-pipelines.yml

Azuredevops iac project

---

src/main/env/uat/terraform.tfvars

Added three api keys
Enable access for a common sandboxed test and to self care
---

Add self care and sandox api keys

---

src/main/14-dynamodb-alarms.tf
src/main/README.md

Dynamodb alerts

---

src/main/05-task-tokenizer.tf

Tasks healthchecks

---

src/main/32-api-tokenizer.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/prod/terraform.tfvars

Log retentions

---

src/main/env/uat/terraform.tfvars

Add api key to interop product
---

Add api key due to interop

---

src/main/09-ecs-as-alerts.tf

Remove sns topic in low cpu alert

---

src/main/05-task-tokenizer.tf

Remove task health check

---

README.md
src/main/11-certs.tf
src/main/20-public-dns.tf
src/main/98-variables.tf

Update dns ttl records

---

src/main/41-nlb-alarms.tf
src/main/README.md

Nlb alarms 

---

src/main/32-api-tokenizer.tf
src/main/api/ms_tokenizer/api-docs.tpl.json
src/main/api/ms_tokenizer/status_code_mapping.tpl.json

Api status mappings

---

src/main/api/ms_tokenizer/api-docs.tpl.json
src/main/api/ms_tokenizer/status_code_mapping.tpl.json

@uolter ho visto che non in tutte le API è presente il 429 come possibile response code, è corretto? Tale policy è stata configurata solo per un subset di API?
---

fix response codes

---

src/main/env/uat/terraform.tfvars

Add a new api key to product Sign IO
---

request to add a new api key due to IO Sign

---

src/main/api/ms_tokenizer/api-docs.tpl.json

remove rootToken field from response model

---

src/main/env/prod/terraform.tfvars

Api test key

---

src/main/cloudwatch-query/count-api-rate-limit.sql

Refactoring query count rate limit

---

src/init/README.md
src/init/main.tf

Block all public access to s3 bucket

---

src/main/.terraform.lock.hcl
src/main/env/uat/terraform.tfvars
src/pipelines/deploy-pipelines.yml

Added api key request for idpay due to dev and uat prod
A new org project
---

Add api key on tokenizer for idpay

---

src/main/README.md
src/main/outputs.tf

Output queue url and cloud trail arn for sentinel config

---

src/main/60-sentinel.tf
src/main/README.md

Update sentinel module v1.0.1

---

src/main/env/prod/terraform.tfvars

Disabled sentinel in production

---

src/main/50-cloudwatch.tf
src/main/README.md
src/main/cloudwatch-query/log-by-traceid.sql

Ecs logs by traceid

---

src/main/20-public-dns.tf

Update ns records

---

src/main/env/prod/terraform.tfvars

Ipday key config

---

src/main/14-dynamodb-alarms.tf
src/main/env/prod/terraform.tfvars

config: Update scaling policy tokenizer table

---

src/main/04-ecs.tf
src/main/05-task-tokenizer.tf
src/main/98-variables.tf
src/main/env/prod/terraform.tfvars

cofnig: Ecs autoscaling change config

---

src/main/04-ecs.tf

fix: Missed cooldown in memory autoscaling

---

src/main/.terraform.lock.hcl

fix: Update terraform hcl file

---

src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

config: Api key PN Persone giuridiche

---

src/main/dashboards/main.tpl.json

fix: Query rate limit dashboard cw

---

src/main/32-api-tokenizer.tf

 fix plan ids shown within the dashboard

---

src/main/32-api-tokenizer.tf
src/main/dashboards/main.tpl.json
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Config changes for UAT load tests IDPAY

---

src/main/32-api-tokenizer.tf

fix: Dashboard plan ids

---

src/azuredevops/98-variables.tf
src/init/README.md
src/init/env/prod/terraform.tfvars
src/init/env/uat/terraform.tfvars
src/init/main.tf
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Renamed repository

---

src/main/iam_policies/deploy-ecs.json.tpl

fix: Missed deploy policy actions

---

src/main/cloudwatch-query/apigw-429.sql
src/main/cloudwatch-query/count-api-rate-limit.sql

fix: Log insight query that gets 429 errors

---

src/main/env/prod/terraform.tfvars

feat: Update idpay plan rate limit

---

src/main/32-api-tokenizer.tf
src/main/33-api-docs.tf
src/main/README.md

fix: Open api export missed descriptions

---

src/main/.terraform.lock.hcl
src/main/00-main.tf
src/main/31-api-keys.tf
src/main/32-api-tokenizer.tf
src/main/33-api-docs.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Allow a plan to have more than one key

---

src/main/.terraform.lock.hcl
src/main/dashboards/main.tpl.json

fix: Changed log insight query in cloudwatch dashboard

---

src/main/env/uat/terraform.tfvars

feat: New api key PNPF-CERT uat

---

src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: New api keys ppa ecom

---

src/main/env/prod/terraform.tfvars

feat: Enable log confidential filter and INFO level

---

src/main/env/prod/terraform.tfvars

changed desired count task from 2 to 3

---

src/main/40-nlb.tf

feat: Update nlb health check interval

---

src/main/05-ecs.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Enable container insights uat

---

src/main/13-eventbridge.tf

feat: Filter criteria definition in event bridge pipe

---

src/main/06-task-tokenizer.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/uat/terraform.tfvars

feat: Higher cpu task definition

---

src/main/06-task-tokenizer.tf
src/main/env/uat/terraform.tfvars

fix: Tokenizer container memory

---

src/main/dashboards/main.json.bak
src/main/dashboards/main.tpl.json

fix: Dashboard widget stats

---

src/main/05-ecs.tf
src/main/dashboards/main.json.bak
src/main/dashboards/main.tpl.json

fix: Scaling mem thrashhold

---

src/main/13-eventbridge.tf

feat: Update event bridge transformation template

---

src/main/32-api-tokenizer.tf

feat: Update apigw alarm

---

src/main/.terraform.lock.hcl
src/main/00-main.tf
src/main/02-network.tf
src/main/13-eventbridge.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/uat/terraform.tfvars

feat: Uat dynamo db scale in

---

src/main/13-eventbridge.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/uat/terraform.tfvars

feat: Policy which allows the datalake to receive messages from the sqs queue

---

src/main/13-eventbridge.tf
src/main/env/uat/terraform.tfvars

fix: Sqs policy not valid

---

src/main/env/prod/terraform.tfvars

feat: Increase memory and cpu in task definition prod

---

src/main/env/uat/terraform.tfvars

feat: Update rate limit PN

---

CODEOWNERS

Update CODEOWNERS file removing infrastracture-admins from it
OER task
---

chore: Update CODEOWNERS file removing infrastracture-admins from it

---

.github/workflows/release.yml
.github/workflows/terraform-apply.yml
.github/workflows/terraform-plan.yml

Pin **ubuntu** version into Github Actions to `ubuntu-22.04`
OER task
---

chore: Oe 62 pin ubuntu version to ubuntu-22.04

---

src/main/34-webacl.tf

fix: Update webacl count alarm

---

src/main/api/request_template.tftpl

This PR updates the template velocity to override x-amzn-trace-id header from incoming requests.
Bug fixing.
---

update: Override x-amzn-trace-id header in request_template.tftpl

---

README.md

chore: Oe 78 add pipelines status badges

---

.github/workflows/terraform-apply.yml
.github/workflows/terraform-plan.yml
src/init/env/dev/backend.tfvars
src/init/env/dev/terraform.tfvars
src/init/main.tf
src/main/11-certs.tf
src/main/20-public-dns.tf
src/main/70-storage.tf
src/main/README.md
src/main/env/dev/backend.tfvars
src/main/env/dev/terraform.tfvars

feat: Dev env first draft

---

src/main/80-alarms.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/prod/terraform.tfvars

feat: Opsgenie topic subscription.

---

src/main/env/dev/terraform.tfvars
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

Add `GITHUB-KEY` plan
This API Key is needed in the integration tests pipeline
---

feat: Add GitHub api key for testing purposes

---

src/main/01-locals.tf
src/main/32-api-tokenizer.tf
src/main/51-dashboard.tf
src/main/80-alarms.tf
src/main/dashboards/main.tpl.json

feat: Update sns policy filter and refactory dashboard cw

---

src/main/32-api-tokenizer.tf

feat: Update apigw latency alarm

---

src/main/32-api-tokenizer.tf

This change also disable sanding alarm 4xx to opsgenie.
---

feat: Update 4xx alarm description

---

src/main/06-task-tokenizer.tf
src/main/env/dev/terraform.tfvars
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Remove var REST_CLIENT_LOGGER_LEVEL

---

src/init/.terraform.lock.hcl
src/main/.terraform.lock.hcl
src/main/50-cloudwatch.tf
src/main/api/request_template.tftpl
src/main/cloudwatch-query/log-by-traceid.sql
src/main/cloudwatch-query/log-by-x-amzn-traceid.sql

This PR introduces the subsequent changes:
- Modifies _Log by Trace Id_ query in `Log Insights` according to the new Log pattern introduced by the application Spring Boot upgrade.
- Introduces new _Log by xAmznTraceId_ query in `Log Insights`
- Remove hotfix from request template
---

fix: Pdv 101 aggiornare query su log insights per gestire nuovo log pattern

---

src/main/32-api-tokenizer.tf

feat: Update alarm 5xx error evaluation period

---

src/main/.terraform.lock.hcl
src/main/00-main.tf
src/main/12-dynamodb-token.tf
src/main/40-nlb.tf
src/main/README.md
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: New key for Pagopa uat and prod

---

src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Renamed ppa keys for ricevute

---

src/main/README.md
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: Update dynamodb provisioning

---

src/main/env/prod/terraform.tfvars

feat: Update dynamodb autoscling and provisioned capacity

---

src/main/03-ecr.tf
src/main/98-variables.tf
src/main/99-outputs.tf
src/main/README.md
src/main/env/prod/terraform.tfvars

feat: New ecr repository to store x-ray agent

---

src/main/.terraform.lock.hcl
src/main/02-network.tf
src/main/03-ecr.tf
src/main/04-iam.tf
src/main/06-task-tokenizer.tf
src/main/32-api-tokenizer.tf
src/main/98-variables.tf
src/main/README.md
src/main/env/dev/terraform.tfvars
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

Pdv 115 add x ray daemon to tokenizer task

---

src/main/dashboards/main.tpl.json

Update cloudwatch dashboard

---

src/main/.terraform.lock.hcl
src/main/00-main.tf
src/main/12-dynamodb-token.tf
src/main/14-dynamodb-alarms.tf
src/main/20-public-dns.tf
src/main/32-api-tokenizer.tf
src/main/34-webacl.tf
src/main/41-nlb-alarms.tf
src/main/97-refactor.tf
src/main/98-variables.tf
src/main/README.md
src/main/cloudwatch-query/log-by-traceid.sql
src/main/cloudwatch-query/log-by-x-amzn-traceid.sql
src/main/env/dev/terraform.tfvars
src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

We are testing DynamoDb with On Demand mode in **UAT**
---

Test dynamodb ondemand

---

src/main/02-network.tf
src/main/14-dynamodb-alarms.tf

Update dynamodb alarm threshold.

---

src/main/env/uat/terraform.tfvars

Disable dynamodb stream uat

---

src/main/14-dynamodb-alarms.tf

Dynamodb throughput alarm remove

---

src/main/api/ms_tokenizer/api-docs.json.tftpl

[PDV-142] Put method does non need 404 response code

---

src/init/README.md
src/init/main.tf

Remove iam user no more required

---

src/main/env/uat/terraform.tfvars

New api key for io-walltet

---

src/main/env/uat/terraform.tfvars

New api key session. wallet pagoPa UAT

---

src/main/env/prod/terraform.tfvars

Api key pagopa wallet PROD

---

src/main/32-api-tokenizer.tf

[PDV-148 ]Errori 500 threshold Tokenizer

---

src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

feat: New key IO Auth

---

src/main/env/prod/terraform.tfvars
src/main/env/uat/terraform.tfvars

Raise rate limit for IO AUTH

---

src/main/env/uat/terraform.tfvars

feat: New api key ebollo 2.0

---

src/main/.terraform.lock.hcl
src/main/12-dynamodb-token.tf

[PDV-163] Weekly backup with monthly and annual retentions

---

src/main/12-dynamodb-token.tf

fix: Backup iam role

---

src/main/35-plan-usage.tf

fix missed policy attachment

---

src/main/35-plan-usage.tf

fix iam policy for lambda execution role

---

src/main/51-dashboard.tf
src/main/97-refactor.tf
src/main/dashboards/usage_plans.tpl.json

feat: First draft dashboard usage plans

---

src/main/01-locals.tf
src/main/35-plan-usage.tf
src/main/51-dashboard.tf
src/main/dashboards/usage_plans.tpl.json

feat: Add random color to the plan labels

---

src/main/35-plan-usage.tf
src/main/dashboards/usage_plans.tpl.json

feat: Update role trusted policy
